### ISSUE TITLE
New project/app name?

### ISSUE THREAD

**Issue by Atemu** [SpartanJ/ImgurViewer#10]
The "ImgurViewer" name is a bit inappropriate now that it supports so many websites ;)

I'm also not sure how much Imgur appreciates their name being used for this purpose.   
IANAL but the "Imgur" name is trademarked and this project doesn't fall under the allowed uses without explicit permission: https://help.imgur.com/hc/en-us/articles/202062878-Trademark-Use-Policy

"OpenViewer" would be fitting IMO, it even gives a little hint at how the app is supposed to be used.  
A quick Google search revealed no relevant, popular or even maintained projects by that name.

Changing the name is quite disruptive, so it'd be better to do this before the app really takes off, which, to me, it seems like it's right on the verge of.

**Comment by SpartanJ** [comment]
I think this project enters into the fair use spectrum, but I'm not really sure. I don't think this app will ever take off since it's a niche app. Changing the name would require quite a lot of work, I'm not against it, but I don't have the time at the moment to make the necessary changes. I'll keep the issue open to check again this in the near future. Imgur it's not aggressive with this kind of trademark protection and I don't think they will change that behavior soon, you'll find several projects using the Imgur word in their project name. But you made a fair point, so I'll keep it in mind.

**Comment by SpartanJ** [comment]
I'll close this for the moment.
