### ISSUE TITLE
[UI/UX Issue] App loading times

### ISSUE THREAD

**Issue by Atrate** [SpartanJ/ImgurViewer#3]
OS: Android 10
App version: 2.1.7

When clicking on links in apps that would open ImgurViewer, nothing happens for a very long time, only after about 10-30s does IV open.

If the link is clicked multiple times, IV opens multiple times as well.

This might be due to very poor network conditions, but the app should still open immediately and just show a loading screen.

**Comment by SpartanJ** [comment]
Hi! I don't think that's actually a problem with ImgurViewer. Your guess is logical but that's not how it behaves the application. In order to be able to start loading any resource, the application requires to open an activity, and in consequence also shows the loader. I made some tests, with the simulated scenario of a low bandwidth connection but I can't replicate it neither. There must be something else that generates an abnormal scenario where that happens. I think we can guess this is not normal because I would have seen the problem much sooner, people is usually very vocal on the play store when something is very wrong.
The behaviour of the app opening multiple times is clicked multiple times is correct, and it's managed by Android.
I don't know exactly what can we do to try to solve your particular scenario, can you try to open the links by sharing the link to ImgurViewer instead of opening normally? The same delay happens even if you open the application manually? You have a big delay when pasting a link in the application?

**Comment by Atrate** [comment]
> can you try to open the links by sharing the link to ImgurViewer instead of opening normally?

The delay is still there

> The same delay happens even if you open the application manually?

Nope, app opens instantly

> You have a big delay when pasting a link in the application?

Yes

Extra info that might be relevant:

- No Google Play Services
- Using a Wireguard kernel-backend supported VPN

**Comment by SpartanJ** [comment]
I still have no clue what's going on. I've been looking a little bit more and I don't find anything that can provoke this. All the HTTP requests are being done asynchronously, the UI should never be delayed. But taking into account that you are using a Wireguard VPN everything indicates that's something related to that particular scenario. My guess is that it must be something at the level of the domain name resolution. But it seems that I will not be able to reproduce it, I personally use also a VPN (no Wireguard though), but never seen any delay at all.
I think to be able to have a better idea of what's happening I would need to see your personal adb log, since there's no crash, I need to see a plain log. But in that case, you would need to know how to capture it and send it to me. If you know how to do it, please do that, otherwise, I'm kind of blindfolded.
One more question: this happens with all kinds of media? Do images and videos show the same behavior?

**Comment by Atrate** [comment]
> this happens with all kinds of media? Do images and videos show the same behavior

Yep.

And sure, I can send a logcat, just later today or tomorrow

**Comment by SpartanJ** [comment]
@Atrate If you are still having the same issue please collect me some logs so I can analyze them. Thanks!

**Comment by SpartanJ** [comment]
Closed due to inactivity. @Atrate feel free to revive this issue anytime.
