### ISSUE TITLE
Low Resolution (Reddit Videos)

### ISSUE THREAD

**Issue by HyknuF** [SpartanJ/ImgurViewer#4]
Thanks for your awesome app! 

I am just facing low resolutions when playback reddit videos. I'm pretty sure that the actual quality of those videos are quiter higher.

Is it just me, or is it possible to increase that?

Thanks in advance!

**Comment by HyknuF** [comment]
![Screenshot_Slide_20200613-232933_1](https://user-images.githubusercontent.com/53949193/84579499-740b7e80-adce-11ea-9f4c-a17ddba7152e.png)

Heres a Screenshot of the thumbnail-quality (on the left) and the playback resolution. hope you can recognize it :-)

**Comment by SpartanJ** [comment]
Yes, you're correct, sadly I can't do much about it. The thing is that the single file videos with audio are usually distributed in very crappy quality. The application is already trying to load the best quality video available, but there's no way to know the quality of the HLS video distributed. I could try to first load the DASH formatted videos instead of the HLS, but they're usually really bad. reddit videos is absolute crap, that's the sad reality. You can send me the video example link, I can check which version with video and sound is the best quality.

**Comment by HyknuF** [comment]
Ah ok, i see, thanks anyway! the example link: https://v.redd.it/ofbt8h7f5p451

**Comment by SpartanJ** [comment]
There was an issue also with the HLS player, it was selecting a low-quality video track. So the problem should be fixed in the next release. I'll test it a little bit more before releasing a new version.

**Comment by HyknuF** [comment]
I am quite happy to hear that. Thanks a lot! :-)
