### ISSUE TITLE
Downloaded files will be saved under Android/data directory on Android13

### ISSUE THREAD

**Issue by neofalia** [SpartanJ/ImgurViewer#77]
When downloading images and videos, they are saved in
`/storage/emulated/Android/data/com.ensoft.imgurviewer/files/Download`
instead of
`/storage/emulated/Download`.

[App version]
2.3.7 (download from Google Play)

[Environment]
Android13 (ZenUI and MyOS, this occurs in both)

On MyOS, this phenomenon occurred from the first installation.
On ZenUI, I was able to save it to `/storage/emulated/Download` until I initialized the app, probably because the settings had been migrated through data transfer.

**Comment by ihatemakinganaccount** [comment]
@SpartanJ how's it going? 🙏

**Comment by SpartanJ** [comment]
Sorry but I don't have Android 13 and honestly I don't download anything with the app, so I never felt the need to fix it, this application is maintenance-mode, I'll basically fix what I feel the need to fix because I need it, but I'm not interested in continue working actively on the application for several reasons, but the main reason is that I don't like the road that Google took with Android, for example on this bug, this happened because Google changed all the permissions levels and directory access for the applications, I you want to have write access to a more "public" directory you'll have to request permission to Google before uploading a new version to the Play Store, I think this is kind of crazy, I don't agree and I'll not actively fight against this horrendous decisions by Google, we should strive for a more open mobile OS, meanwhile I'll not waste time fixing "bugs" that are not actually bugs but direct design decisions from Google.
If anyone is willing to send a PR that fixes the issue I'm more than willing to accept it, but meanwhile this is it for ImgurViewer, I'm focusing on [other](https://github.com/SpartanJ/ecode/) [projects](https://github.com/SpartanJ/eepp) right now and I don't have enough time to take care of this one.

**Comment by ihatemakinganaccount** [comment]
@SpartanJ well that's a bummer. Thanks for the app tho, I've been using it for quite a while. Hopefully someone will pick it up.

**Comment by woheller69** [comment]
You might add permission MANAGE_EXTERNAL_STORAGE permission to your manifest, **as long as you do not want to publish on GooglePlay**.

Request all-files access
An app can request all-files access from the user by doing the following:

Declare the [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#MANAGE_EXTERNAL_STORAGE) permission in the manifest.
Use the [ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION) intent action to direct users to a system settings page where they can enable the following option for your app: Allow access to manage all files.
