### ISSUE TITLE
Imgur Gallery not opening.

### ISSUE THREAD

**Issue by noobbuild** [SpartanJ/ImgurViewer#8]
Just a com.android.volley.ClientError and infinite loading animation after that. Happens in both list and thumbnail view.

**Comment by KaKi87** [comment]
Hi,
I'm currently experiencing the same issue on the latest version.
Thanks

**Comment by SpartanJ** [comment]
@KaKi87 I'm not using the application anymore so I'm not maintain it either, I expect some things to be broken since services API change all the time. Although I just tried and imgur and reddit galleries are working for me, so maybe you can send me an example, I don't promise I'll fix it but at least to acknowledge if something is currently broken.

**Comment by KaKi87** [comment]
> I'm not using the application anymore

What do you use instead to open images and videos without opening those bloated websites then ?

> you can send me an example

So actually I can't find yesterday's link, but here's a new error : https://paste.crdroid.net/g4ghzh

When trying to play any image in this link : https://imgur.com/a/DV2BJVI

Thank you
